ModelType: 'MAF'
Transform: 'Affine'
optimizer: 'Adam'
num_cond_inputs: 1
num_layers: 4
num_blocks: 8
num_hidden: 256
activation_function: 'tanh'
pre_exp_tanh: false
batch_norm: true
batch_norm_momentum: 1

optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.000001


# 2_237_056 trainable params