ModelType: 'MAF'
Transform: 'RQS'
optimizer: 'Adam'
num_layers: 1
num_blocks: 12
num_hidden: 256
num_bins: 16
activation_function: 'tanh'
pre_exp_tanh: false
batch_norm: true
batch_norm_momentum: 1

optimizer:
  name: Adam
  lr: 0.0001 #0.001
  weight_decay: 0.000001


# 1_532_796